### ISSUE TITLE
[Bug]: Quilt crashes when attempting to launch a rocket

### ISSUE THREAD

**Issue by MichailiK** [terrarium-earth/Ad-Astra#115]
### Bug Description

When attempting to launch a rocket using Quilt and QSL, the game will not play any sound, and the console will print the following `OutOfMemoryError` exception:
```
[Sound engine/ERROR]: Uncaught exception in thread "Sound engine"
 java.lang.OutOfMemoryError: null
 	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?] 
	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:241) ~[lwjgl-3.3.1.jar:build 7]
 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:265) ~[lwjgl-3.3.1.jar:build 7]
 	at net.minecraft.client.sound.OggAudioStream.increaseBufferSize(OggAudioStream:134) ~[?:?]
 	at net.minecraft.client.sound.OggAudioStream.readOggFile(OggAudioStream:159) ~[?:?]
 	at net.minecraft.client.sound.OggAudioStream.getBuffer(OggAudioStream:224) ~[?:?]
 	at net.minecraft.client.sound.Source.read(Source:151) ~[?:?]
 	at net.minecraft.client.sound.Source.setStream(Source:140) ~[?:?]
 	at net.minecraft.client.sound.SoundSystem.method_19755(SoundSystem:459) ~[?:?]
 	at net.minecraft.client.sound.Channel$SourceManager.method_19737(Channel:34) ~[?:?]
 	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
 	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
 	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
 	at net.minecraft.client.sound.SoundExecutor.waitForStop(SoundExecutor:42) ~[?:?]
 	at java.lang.Thread.run(Thread.java:833) [?:?]
```

If you left-clicking at any point after trying to launch, the game will freeze.

### How to Reproduce?

1. Use Quilt as your mod loader
2. Use QSL
3. Attempt to launch a Tier 1 rocket

### Expected Behavior

-

### Version

1.19.1

### Mod Loader Version

0.18.1-beta.25

### Mod Loader

Quilt

### Logs or additional context

Logs: https://mclo.gs/tEZmI5k

Video demonstration:

https://user-images.githubusercontent.com/39029839/210153252-550f2c24-a270-44f4-976e-1f6dbcf945a4.mp4

#### Workarounds
- Turning off sounds prevents this crash, i.e. setting Master Volume to OFF in Minecraft's audio settings.

**Comment by AlexNijjar** [comment]
does it still happen on the latest quilt version? all ad astra does is stream a 1.3mb sound file so I don't know how that's even happening. and it's only quilt, not fabric so I'm guessing they have their own sound system

**Comment by MichailiK** [comment]
I've just updated Quilt Loader & QSL to `0.18.3` and `5.0.0-beta.8+0.75.1-1.19.3` respectively. The issue is fixed & the rockets/sounds work as expected in these versions. Cheers!

**Comment by AlexNijjar** [comment]
awesome
