### ISSUE TITLE
Crashing when loading the player

### ISSUE THREAD

**Issue by Stick404** [terrarium-earth/Ad-Astra#14]
when ever I look at the player wearing the space suits my game crashes, but only when im on a server 
here is the crash:

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1304.method_5925()" because "$$0" is null
	at net.minecraft.class_1657.method_6118(class_1657.java:1912)
	at net.minecraft.class_970.handler$dcp000$getArmorTexture(class_970.java:2083)
	at net.minecraft.class_970.method_4174(class_970.java:119)
	at net.minecraft.class_970.method_23192(class_970.java:105)
	at net.minecraft.class_970.cosmeticarmor$renderArmor(class_970.java:615)
	at net.minecraft.class_970.md84003a$lambda$renderCustomArmor$1$0(class_970.java:569)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_970.handler$caj000$renderDelayed(class_970.java:580)
	at net.minecraft.class_970.method_17157(class_970.java:39)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.redirect$znj000$preventFeatureRendering(class_922.java:1063)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:64)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

 And the full crash report https://pastebin.com/qpw3R2cD

**Comment by AlexNijjar** [comment]
Hey! Is this still happening? I've been unable to reproduce it. What performance mods are you using?

**Comment by Stick404** [comment]
After doing a full reset of the server (Deleting the world and making a new one) it is no longer happening.
