### ISSUE TITLE
[Bug]: Game crash when punching lander

### ISSUE THREAD

**Issue by Marix20** [terrarium-earth/Ad-Astra#155]
### Bug Description

Game crashes when punching lander.

I've also tried removing items from lander before punching.

No other mods were being used at the time of the crash, other than dependencies.

### Version

1.13.3

### Mod Loader Version

1.19.3 - 44.1.4

### Mod Loader

Forge

### Logs or additional context

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-01-16 23:45:47
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class earth.terrarium.ad_astra.common.item.vehicle.VehicleItem (net.minecraft.world.item.AirItem is in module minecraft@1.19.3 of loader 'TRANSFORMER' @46f902e0; earth.terrarium.ad_astra.common.item.vehicle.VehicleItem is in module ad_astra@1.13.3 of loader 'TRANSFORMER' @46f902e0)
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.drop(Vehicle.java:245) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at earth.terrarium.ad_astra.common.entity.vehicle.Lander.drop(Lander.java:45) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.m_6469_(Vehicle.java:229) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1145) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:401) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1623) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1793) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1097) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.drop(Vehicle.java:245) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at earth.terrarium.ad_astra.common.entity.vehicle.Lander.drop(Lander.java:45) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.m_6469_(Vehicle.java:229) ~[ad_astra-forge-1.19.3-1.13.3.jar%23152!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1145) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:401) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1623) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Marix20'/1, l='ClientLevel', x=-4.08, y=103.00, z=4.61]]
	Chunk stats: 1225, 613
	Level dimension: ad_astra:moon
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2076 game time, 2076 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:452) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.19.3-20221207.122022-srg.jar%23156!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 669963856 bytes (638 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2191
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1278
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=26.20.100.7985
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18598.52
	Virtual memory used (MB): 15067.32
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 424.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.3-forge-44.1.4
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 26.20.100.7985, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Marix20'/1, l='ServerLevel[Astra Testing]', x=-4.08, y=103.00, z=4.61]]
	Data Packs: vanilla, mod:resourcefulconfig, mod:forge, mod:resourcefullib (incompatible), mod:botarium, mod:ad_astra (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.1.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.1.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.1.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		resourcefulconfig-forge-1.19.3-1.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |1.1.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.3-44.1.4-universal.jar                 |Forge                         |forge                         |44.1.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		resourcefullib-forge-1.19.3-1.2.5.jar             |Resourceful Lib               |resourcefullib                |1.2.5               |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.19.3-2.0.4.jar                   |Botarium                      |botarium                      |2.0.4               |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.19.3-1.13.3.jar                  |Ad Astra!                     |ad_astra                      |1.13.3              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 08c8f94b-8084-40af-9fa7-25ad10597e16
	FML: 44.1
	Forge: net.minecraftforge:44.1.4

**Comment by MicheleBerretti** [comment]
Fabric too is affected by this bug. 

@Marix20 Do you have a list of installed mods on your system? It could be due to some weird behaviour with one of the already installed mods.
Looking for some mods in common between the two of us could be useful.

**Comment by Marix20** [comment]
Ad Astra
Resourceful Config
Botarium
Resourceful Lib

The first time I ran it the mod, I did have other  mods installed, but removed them and still had the same issue.

**Those mods were:**
Xaeros World Map
Xaeros_Minimap
Nullscape 1.2a
Croptopia 2.2.1
Ecologics (Forge) 2.1.12
Immersive Aircraft 0.2.1
Iron Bows 1.5
Wooled Boots 1.5
Tool Leveling+ (Forge) 1.4.4
Immersive Armors 1.5.2
Sit 1.3.3
Blue Skies 1.3.21
Structure Gel 2.8.0
Wabi Sabi Structures (Forge) 1.1.2
Domestication Innovation 1.7.0
Falling Tree 3.11.1
Jade 9.2.2
Citadel 2.2.0
Alex's Mobs 1.22.0
Aquaculture 2.4.9

**Comment by AlexNijjar** [comment]
It's fixed I'll release an update soon
