### ISSUE TITLE
[Bug]: Game Crash When Activating

### ISSUE THREAD

**Issue by Saremix** [terrarium-earth/Ad-Astra#180]
### Bug Description

Code 1 Nothing More Do I Need Any Mod I Only Have JEI And Ad Astra Installed 

### Expected Behavior

Game Normally Launch

### Version

1.13.3

### Mod Loader Version

1.19.3 1.13.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Ad Astra has 3 dependencies
https://www.curseforge.com/minecraft/mc-mods/resourceful-lib
https://www.curseforge.com/minecraft/mc-mods/resourceful-config
https://www.curseforge.com/minecraft/mc-mods/botarium

**Comment by IndigobyJas** [comment]
I tried this and it resulted in error 1
<img width="714" alt="image" src="https://user-images.githubusercontent.com/110175731/218151991-331ad871-1b06-485a-80b0-006e08609f23.png">

**Comment by AlexNijjar** [comment]
sending the exit code doesn’t help. send the latest.log file. you probably accidentally installed one of the fabric versions or something

**Comment by IndigobyJas** [comment]
here it is

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 17/12/21 12:57
Description: Initializing game

java.lang.IllegalStateException: GLFW error before init: [0x10008]Cocoa: Failed to find service port for display
	at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1060) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:416) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4-forge-35.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1060) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:416) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4-forge-35.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1202642296 bytes (1146 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.4-forge-35.1.4
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
