### ISSUE TITLE
[Bug]: Crash on startup 

### ISSUE THREAD

**Issue by Thesimpledude42** [terrarium-earth/Ad-Astra#215]
### Bug Description

Caused by: java.util.zip.ZipException: zip END header not found
Only running Ad Astra with its dependencies
Minecraft version 1.19.2
Using Tlauncher (if it has anything to do with this)

### Version

1.12.3

### Mod Loader Version

 43.2.4

### Mod Loader

Forge

### Logs or additional context

[Launcher] Launching Minecraft...
I'm hiding!
[TLauncherManager] mods after C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\mods\ad_astra-forge-1.19.2-1.12.3.jar C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\mods\botarium-forge-1.19.2-1.8.2.jar C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\mods\resourcefulconfig-forge-1.19.2-1.0.19.jar C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\mods\resourcefullib-forge-1.19.2-1.1.22.jar C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\mods\tl_skin_cape_forge_1.19_1.19.2-1.27.jar
[Launcher] skin system is activated: true
[Launcher] Starting Minecraft 1.19.2 aaa...
[Launcher] Launching in: C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa
Starting garbage collector: 225 / 427 MB
Garbage collector completed: 72 / 418 MB
[Launcher] Processing post-launch actions. Assist launch: true
===============================================================================================
[16:56:00] [main/INFO]: ModLauncher running: args [--username, TheSimpleDude42, --version, 1.19.2 aaa, --gameDir, C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa, --assetsDir, C:\Users\Frost\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 33014cbe62a44bb3a3795d914e33857c, --accessToken, вќ„вќ„вќ„вќ„вќ„вќ„вќ„вќ„, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 1280, --height, 720, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.4, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[16:56:00] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.util.zip.ZipException: zip END header not found
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1534)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:475)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:112)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:107)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:61)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (97 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\crash-reports\crash-2023-03-02_16.41.07-client.txt
[Crash] Found crash report file: C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\crash-reports\crash-2023-03-02_16.41.07-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\crash-reports\crash-2023-03-02_16.42.22-client.txt
[Crash] Found crash report file: C:\Users\Frost\AppData\Roaming\.minecraft\versions\1.19.2 aaa\crash-reports\crash-2023-03-02_16.42.22-client.txt
flush now

**Comment by AlexNijjar** [comment]
we don't support Tlauncher.
