### ISSUE TITLE
[Bug]: Crashes with Apace's Cosmetic Armor.

### ISSUE THREAD

**Issue by snowstorm174** [terrarium-earth/Ad-Astra#520]
### Bug Description

Attempting to wear cosmetic armor over a space suit causes the game to crash. 

### How to Reproduce?

Equip a piece of armor on the cosmetic armor slot and space suit armor piece in the main slot, the game will crash.

### Expected Behavior

Cosmetic armor to show rather than the space suit and for the game to not crash.

### Version

1.16.5

### Mod Loader Version

1.20.4 - 0.15.6

### Mod Loader

Fabric

### Logs or additional context

[19:52:33] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[19:52:33] [main/INFO]: Loading 67 mods:
	- ad_astra 1.16.5
	   \-- javazoom_jlayer 1.0.1
	- botarium 3.0.8
	   \-- team_reborn_energy 3.0.0
	- cosmetic-armor 1.6.0
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.4
	- resourcefulconfig 2.4.5
	- resourcefullib 2.4.10
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- trinkets 3.8.1
	   |-- cardinal-components-base 5.4.0
	   \-- cardinal-components-entity 5.4.0
[19:52:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:52:34] [main/INFO]: Compatibility level set to JAVA_17
[19:52:35] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[19:52:39] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 138 milliseconds
[19:52:41] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:52:41] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[19:52:43] [Render thread/ERROR]: No data fixer registered for tier_1_rover
[19:52:43] [Render thread/ERROR]: No data fixer registered for tier_1_rocket
[19:52:43] [Render thread/ERROR]: No data fixer registered for tier_2_rocket
[19:52:43] [Render thread/ERROR]: No data fixer registered for tier_3_rocket
[19:52:43] [Render thread/ERROR]: No data fixer registered for tier_4_rocket
[19:52:43] [Render thread/ERROR]: No data fixer registered for lander
[19:52:43] [Render thread/ERROR]: No data fixer registered for lunarian
[19:52:43] [Render thread/ERROR]: No data fixer registered for corrupted_lunarian
[19:52:43] [Render thread/ERROR]: No data fixer registered for star_crawler
[19:52:43] [Render thread/ERROR]: No data fixer registered for martian_raptor
[19:52:43] [Render thread/ERROR]: No data fixer registered for pygro
[19:52:43] [Render thread/ERROR]: No data fixer registered for zombified_pygro
[19:52:43] [Render thread/ERROR]: No data fixer registered for pygro_brute
[19:52:43] [Render thread/ERROR]: No data fixer registered for mogler
[19:52:43] [Render thread/ERROR]: No data fixer registered for zombified_mogler
[19:52:43] [Render thread/ERROR]: No data fixer registered for lunarian_wandering_trader
[19:52:43] [Render thread/ERROR]: No data fixer registered for sulfur_creeper
[19:52:43] [Render thread/ERROR]: No data fixer registered for glacian_ram
[19:52:43] [Render thread/ERROR]: No data fixer registered for ice_spit
[19:52:44] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[19:52:44] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[19:52:45] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, ad_astra, cardinal-components-base, cardinal-components-entity, cosmetic-armor, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, resourcefulconfig, team_reborn_energy, trinkets
[19:52:45] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[19:52:47] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[19:52:47] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:52:48] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speaker (Realtek(R) Audio)
[19:52:48] [Render thread/INFO]: Sound engine started
[19:52:48] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:52:48] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[19:52:48] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:52:48] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:52:48] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[19:52:48] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[19:52:48] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:52:48] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:52:48] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:52:49] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[19:52:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[19:52:50] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:52:50] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:52:50] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/gui.png-atlas
[19:53:05] [Render thread/INFO]: Loaded 14 recipes
[19:53:05] [Render thread/INFO]: Loaded 1833 advancements
[19:53:20] [Render thread/INFO]: Loaded 14 recipes
[19:53:20] [Render thread/INFO]: Loaded 1834 advancements
[19:53:33] [Render thread/INFO]: Applied 0 biome modifications to 0 of 74 new biomes in 2.166 ms
[19:53:33] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[19:53:33] [Server thread/INFO]: Generating keypair
[19:53:36] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:53:37] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:37] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:39] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:39] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:39] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:39] [Render thread/INFO]: Preparing spawn area: 0%
[19:53:39] [Render thread/INFO]: Preparing spawn area: 1%
[19:53:40] [Render thread/INFO]: Preparing spawn area: 2%
[19:53:40] [Render thread/INFO]: Preparing spawn area: 4%
[19:53:41] [Render thread/INFO]: Preparing spawn area: 6%
[19:53:41] [Render thread/INFO]: Preparing spawn area: 9%
[19:53:42] [Render thread/INFO]: Preparing spawn area: 10%
[19:53:42] [Render thread/INFO]: Preparing spawn area: 15%
[19:53:43] [Render thread/INFO]: Preparing spawn area: 17%
[19:53:43] [Render thread/INFO]: Preparing spawn area: 21%
[19:53:44] [Render thread/INFO]: Preparing spawn area: 23%
[19:53:44] [Render thread/INFO]: Preparing spawn area: 26%
[19:53:45] [Render thread/INFO]: Preparing spawn area: 31%
[19:53:45] [Render thread/INFO]: Preparing spawn area: 34%
[19:53:46] [Render thread/INFO]: Preparing spawn area: 37%
[19:53:46] [Render thread/INFO]: Preparing spawn area: 42%
[19:53:47] [Render thread/INFO]: Preparing spawn area: 45%
[19:53:47] [Render thread/INFO]: Preparing spawn area: 49%
[19:53:48] [Render thread/INFO]: Preparing spawn area: 53%
[19:53:49] [Render thread/INFO]: Preparing spawn area: 54%
[19:53:49] [Render thread/INFO]: Preparing spawn area: 54%
[19:53:49] [Render thread/INFO]: Preparing spawn area: 55%
[19:53:50] [Render thread/INFO]: Preparing spawn area: 56%
[19:53:50] [Render thread/INFO]: Preparing spawn area: 60%
[19:53:51] [Render thread/INFO]: Preparing spawn area: 64%
[19:53:51] [Render thread/INFO]: Preparing spawn area: 68%
[19:53:52] [Render thread/INFO]: Preparing spawn area: 71%
[19:53:52] [Render thread/INFO]: Preparing spawn area: 75%
[19:53:53] [Render thread/INFO]: Preparing spawn area: 79%
[19:53:53] [Render thread/INFO]: Preparing spawn area: 82%
[19:53:54] [Render thread/INFO]: Preparing spawn area: 83%
[19:53:54] [Render thread/INFO]: Preparing spawn area: 85%
[19:53:55] [Render thread/INFO]: Preparing spawn area: 88%
[19:53:55] [Render thread/INFO]: Preparing spawn area: 90%
[19:53:56] [Render thread/INFO]: Preparing spawn area: 95%
[19:53:56] [Render thread/INFO]: Preparing spawn area: 98%
[19:53:56] [Render thread/INFO]: Time elapsed: 20188 ms
[19:53:57] [Server thread/INFO]: Changing view distance to 6, from 10
[19:53:57] [Server thread/INFO]: Changing simulation distance to 6, from 0
[19:53:57] [Server thread/INFO]: {MINECRAFT_USERNAME}[local:E:bef1a996] logged in with entity id 304 at (-6.5, 77.0, -9.5)
[19:53:57] [Server thread/INFO]: {MINECRAFT_USERNAME} joined the game
[19:53:58] [Render thread/INFO]: Loaded 2 advancements
[19:54:10] [Server thread/INFO]: {MINECRAFT_USERNAME} has made the advancement [Cover Me with Diamonds]
[19:54:10] [Render thread/INFO]: [System] [CHAT] {MINECRAFT_USERNAME} has made the advancement [Cover Me with Diamonds]
[19:54:10] [Render thread/INFO]: Loaded 9 advancements
[19:54:27] [Server thread/INFO]: {MINECRAFT_USERNAME} has made the advancement [Astronaut]
[19:54:27] [Render thread/INFO]: [System] [CHAT] {MINECRAFT_USERNAME} has made the advancement [Astronaut]
[19:54:27] [Render thread/INFO]: Loaded 21 advancements
[19:54:38] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_757.method_3192(class_757.java:940) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_8053.method_48428(net.minecraft.class_5455, net.minecraft.class_1799)'
	at net.minecraft.class_970.cosmeticarmor$renderArmor(class_970.java:616) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.md0cdcae$cosmetic-armor$lambda$renderCustomArmor$1$1(class_970.java:572) ~[client-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_970.handler$zcm000$cosmetic-armor$renderDelayed(class_970.java:583) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_17157(class_970.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_4199(class_970.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:144) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_29977(class_490.java:156) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1192) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_48472(class_490.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_2389(class_481.java:831) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25420(class_465.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$179(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$zok000$fabric-screen-api-v1$onRenderScreen(class_757.java:2111) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:931) ~[client-intermediary.jar:?]
	... 6 more
[19:54:38] [Server thread/INFO]: Stopping server
[19:54:38] [Server thread/INFO]: Saving players
[19:54:38] [Server thread/INFO]: {MINECRAFT_USERNAME} lost connection: Disconnected
[19:54:38] [Server thread/INFO]: {MINECRAFT_USERNAME} left the game
[19:54:38] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:54:38] [Server thread/INFO]: Saving worlds
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:earth_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:mercury_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:glacio_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:glacio
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:mars
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:mercury
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:venus_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:moon_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:moon
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:mars_orbit
[19:54:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ad_astra:venus
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (earth_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars_orbit): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus): All chunks are saved
[19:54:39] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
What is Apace? Send the full crash report in a pastebin. I'm also very concerned about this line:
`Caused by: java.lang.NoSuchMethodError: 'java.util.Optional `
