### ISSUE TITLE
[Bug]: Crash with Horse in boat installed

### ISSUE THREAD

**Issue by domanhthang2110** [terrarium-earth/Ad-Astra#54]
### Bug Description

[10:05:32] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed horseinboat.mixins.json:AbstractHorseMixin -> net.minecraft.world.entity.animal.horse.AbstractHorse: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]

### How to Reproduce?

1. Install both Horse in boat (https://modrinth.com/mod/horseinboat) and Ad Astra
2. Launch the game

### Expected Behavior

The game crash with the log below

### Version

1.11.6

### Mod Loader Version

1.19.2 Forge 43.1.52

### Mod Loader

Forge

### Logs or additional context

[22Nov2022`` 10:11:37.331] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, YukamiNeesan, --version, 1.19.2-forge-43.1.52, --gameDir, C:\Users\akuma\AppData\Roaming\.minecraft, --assetsDir, C:\Users\akuma\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 3eeb6e1d923a4917a60cdc58b2eac65f, --accessToken, ????????, --clientId, YTU1Nzk2YjMtMzMxMC00ZWIyLTg4NjktMjUzMjUyNmY2M2Nl, --xuid, 2535468614473446, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.52, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[22Nov2022 10:11:37.335] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[22Nov2022 10:11:37.490] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/akuma/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[22Nov2022 10:11:38.203] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\akuma\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.52\fmlcore-1.19.2-43.1.52.jar is missing mods.toml file
[22Nov2022 10:11:38.205] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\akuma\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.52\javafmllanguage-1.19.2-43.1.52.jar is missing mods.toml file
[22Nov2022 10:11:38.209] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\akuma\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.52\lowcodelanguage-1.19.2-43.1.52.jar is missing mods.toml file
[22Nov2022 10:11:38.213] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\akuma\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.52\mclanguage-1.19.2-43.1.52.jar is missing mods.toml file
[22Nov2022 10:11:38.339] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[22Nov2022 10:11:38.471] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'botarium', Requested by: 'ad_astra', Expected range: '[1.7.10,)', Actual version: '1.7.9'
[22Nov2022 10:11:40.254] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[22Nov2022 10:11:40.350] [main/ERROR] [mixin/]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property
[22Nov2022 10:11:40.431] [main/ERROR] [mixin/]: Mixin config rottencreatures-common.mixins.json does not specify "minVersion" property
[22Nov2022 10:11:40.433] [main/ERROR] [mixin/]: Mixin config rottencreatures.mixins.json does not specify "minVersion" property
[22Nov2022 10:11:40.523] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[22Nov2022 10:11:40.525] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[22Nov2022 10:11:40.526] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2-forge-43.1.52, --gameDir, C:\Users\akuma\AppData\Roaming\.minecraft, --assetsDir, C:\Users\akuma\AppData\Roaming\.minecraft\assets, --uuid, 3eeb6e1d923a4917a60cdc58b2eac65f, --username, YukamiNeesan, --assetIndex, 1.19, --accessToken, ????????, --clientId, YTU1Nzk2YjMtMzMxMC00ZWIyLTg4NjktMjUzMjUyNmY2M2Nl, --xuid, 2535468614473446, --userType, msa, --versionType, release]
[22Nov2022 10:11:40.558] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 29 options available, 0 override(s) found
[22Nov2022 10:11:40.564] [main/WARN] [mixin/]: Reference map 'insanelib.refmap.json' for insanelib.mixins.json could not be read. If this is a development environment you can ignore this message
[22Nov2022 10:11:40.669] [main/WARN] [mixin/]: Reference map 'simplyswords-common-refmap.json' for simplyswords-common.mixins.json could not be read. If this is a development environment you can ignore this message
[22Nov2022 10:11:40.670] [main/WARN] [mixin/]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message
[22Nov2022 10:11:40.683] [main/WARN] [mixin/]: Reference map 'rottencreatures-forge-refmap.json' for rottencreatures.mixins.json could not be read. If this is a development environment you can ignore this message
[22Nov2022 10:11:40.713] [main/WARN] [CanaryConfig/]: Option 'mixin.world.block_entity_ticking.world_border' requires 'mixin.util.world_border_listener=true' but found 'false'. Setting 'mixin.world.block_entity_ticking.world_border=false'.
[22Nov2022 10:11:40.714] [main/INFO] [Canary/]: Loaded configuration file for Canary: 104 options available, 0 override(s) found
[22Nov2022 10:11:41.372] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088
[22Nov2022 10:11:41.372] [main/INFO] [IMixinConfigPlugin/]: Inventory Profiles Next dependency resolution failed! Probably missing libIPN.
[22Nov2022 10:11:41.483] [main/WARN] [mixin/]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net.optifine.shaders.ShadersRender)
[22Nov2022 10:11:41.484] [main/WARN] [mixin/]: @Mixin target net.optifine.shaders.ShadersRender was not found shouldersurfing.mixins.json:MixinShadersRender
[22Nov2022 10:11:41.811] [main/INFO] [ModdingLegacy/Lucent/]: [lucent] Found Create
[22Nov2022 10:11:42.037] [main/INFO] [Smooth Boot (Reloaded)/]: Smooth Boot (Reloaded) config initialized
[22Nov2022 10:11:43.120] [main/WARN] [mixin/]: Discarding @Unique public method getAnimatedSkin in entityculling.mixins.json:DonorAbstractClientPlayerMixin because it already exists in net.minecraft.client.player.AbstractClientPlayer
[22Nov2022 10:11:45.099] [pool-3-thread-1/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[22Nov2022 10:11:45.320] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed horseinboat.mixins.json:AbstractHorseMixin -> net.minecraft.world.entity.animal.horse.AbstractHorse: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: m_20191_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_20191_ ->  -> Validate]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.validateMethod(MixinTargetContext.java:521) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:446) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:532) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:177) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at net.minecraft.client.main.Main.lambda$run$0(Main.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23294!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by AlexNijjar** [comment]
install botarium 
https://www.curseforge.com/minecraft/mc-mods/botarium
