### ISSUE TITLE
[Bug]:  Crashes when Inventory Tabs (https://modrinth.com/mod/inventory-tabs) is present

### ISSUE THREAD

**Issue by Vee-ee** [terrarium-earth/Ad-Astra#597]
### Bug Description

When going to space in any rocket (and with inventory tabs installed) the client throws up a rendering crash. I believe this would be an issue with the way Ad Astra handles the inventory.

### How to Reproduce?

1. Install Ad Astra (1.15.18) and Inventory Tabs (1.3.3+1.20)
2. Place down a rocket, any tier, and go to space
3. Upon exiting Earth's atmosphere, the game will crash.

### Version

1.15.18

### Mod Loader Version

1.20.1 - 0.15.11

### Mod Loader

Fabric

### Logs or additional context

Section of the log where the is present:
"[17:23:23] [Server thread/INFO]: Saving worlds
[17:23:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/minecraft:overworld
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:venus
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:moon
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/minecraft:the_end
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:mercury_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:mars
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:moon_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:mars_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:venus_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/minecraft:the_nether
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:glacio
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:earth_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:glacio_orbit
[17:23:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World2]'/ad_astra:mercury
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World2): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (earth_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio_orbit): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury): All chunks are saved
[17:23:25] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:23:25] [Render thread/INFO]: Stopping JEI
[17:23:25] [Render thread/INFO]: Stopping JEI
[17:23:25] [Render thread/INFO]: Sending Runtime Unavailable...
[17:23:25] [Render thread/INFO]: Stopping JEI GUI
[17:23:25] [Render thread/INFO]: Sending Runtime Unavailable took 433.6 μs
[17:23:25] [Render thread/INFO]: Stopping worker threads
[17:23:25] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.get(Unknown Source) ~[?:?]
	at folk.sisby.inventory_tabs.TabManager.getPageButton(TabManager.java:293) ~[inventory-tabs-1.3.3+1.20.jar:?]
	at folk.sisby.inventory_tabs.TabManager.drawButton(TabManager.java:302) ~[inventory-tabs-1.3.3+1.20.jar:?]
	at folk.sisby.inventory_tabs.TabManager.render(TabManager.java:287) ~[inventory-tabs-1.3.3+1.20.jar:?]
	at net.minecraft.class_465.handler$cjb000$inventory-tabs$render(class_465.java:2719) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:169) ~[client-intermediary.jar:?]
	at earth.terrarium.adastra.client.screens.PlanetsScreen.method_25394(PlanetsScreen.java:204) ~[ad_astra-fabric-1.20.1-1.15.18.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more"

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
See https://github.com/terrarium-earth/ad-astra/issues/445
