### ISSUE TITLE
[Bug]: Crash when dismount from rocket

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#70]
### Bug Description

```
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Unexpected value: 270
	at earth.terrarium.ad_astra.entities.vehicles.Rocket.m_7688_(Rocket.java:109) ~[ad_astra-forge-1.19.2-1.11.8.jar%23146!/:?]
	at net.minecraft.world.entity.LivingEntity.m_21028_(LivingEntity.java:1978) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8127_(LivingEntity.java:2726) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.level.ServerPlayer.m_8127_(ServerPlayer.java:910) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.world.entity.player.Player.m_6083_(Player.java:465) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.level.ServerLevel.m_8662_(ServerLevel.java:678) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:662) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23180!/:?]
	... 5 more
```

### How to Reproduce?

1. Place rocket.
2. Try dismount.

### Expected Behavior

1. Just dismount without crash.

### Version

1.11.8

### Mod Loader Version

1.19.2-43.1.55

### Logs or additional context

https://pastebin.com/vRkG34pY

**Comment by AlexNijjar** [comment]
will be fixed in the next update
